/*
 * Movie Actions
 */
export const SET_SEARCH_MOVIE_TEXT = 'SET_SEARCH_MOVIE_TEXT'
export const SET_SEARCH_MOVIE_SEARCH_BY = 'SET_SEARCH_MOVIE_SEARCH_BY'
export const SET_SEARCH_MOVIE_SORT_BY = 'SET_SEARCH_MOVIE_SORT_BY'

export const FETCH_MOVIES = 'FETCH_MOVIES'
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS'
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE'

export const FETCH_MOVIE = 'FETCH_MOVIE'
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS'
export const FETCH_MOVIE_FAILURE = 'FETCH_MOVIE_FAILURE'

export const FETCH_RELATE_MOVIES = 'FETCH_RELATE_MOVIES'
export const FETCH_RELATE_MOVIES_SUCCESS = 'FETCH_RELATE_MOVIES_SUCCESS'
export const FETCH_RELATE_MOVIES_FAILURE = 'FETCH_RELATE_MOVIES_FAILURE'